# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    env:
      REACT_APP_HOST: http://ec2-44-231-4-226.us-west-2.compute.amazonaws.com:3002/
      GENERATE_SOURCEMAP: false

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: export REACT_APP_HOST=http://ec2-44-231-4-226.us-west-2.compute.amazonaws.com:3002/
      - run: |
          touch .env
          echo REACT_APP_HOST=http://ec2-44-231-4-226.us-west-2.compute.amazonaws.com:3002/ >> .env
          echo GENERATE_SOURCEMAP=false >> .env
      - run: sudo npm run build
