# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    env:
      REACT_APP_BACKEND_URL: http://ec2-35-91-29-142.us-west-2.compute.amazonaws.com:3001/

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: export REACT_APP_BACKEND_URL=http://ec2-35-88-234-153.us-west-2.compute.amazonaws.com:3002/
      - run: npm install
      - run: npm run build
